Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ApiService.DAO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.DAO;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Elementos.DTO;
using Projeto_Estoque.Validações;
using Projeto_Estoque.Enumerador;
namespace Projeto_Estoque.Controllers
{
   
    public class ConsultaController : Controller
    {
       

        private readonly ProdutoDAO _context;
        public ConsultaController(DataContext dataContext)
        {
            _context = new ProdutoDAO(dataContext);
        }

        public IActionResult Consulta(string NomeProduto)
        {

            TipoPerfil tipoPerfil = (TipoPerfil)LoginValidacao.ValidaPerfil();
            ViewData["Message"] = NomeProduto;
            if (tipoPerfil == TipoPerfil.Administrador || tipoPerfil == TipoPerfil.Usuario)
                return View("\\Views\\Home\\Consulta.cshtml");          
            else
            {
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }

        }

        public ActionResult<List<ProdutoDTO>> ConsultaProduto(ProdutoDTO produto)
        {
           
            

            Enumerador.TipoPerfil tipoPerfil = (Enumerador.TipoPerfil) LoginValidacao.ValidaPerfil();

           // List<Produto> listaProdutos =  _context.CarregarProdutos(produto.Nome);
            if (tipoPerfil == Enumerador.TipoPerfil.Usuario || tipoPerfil == Enumerador.TipoPerfil.Administrador)
            {
                
                return View("\\Views\\Home\\Consulta.cshtml");               
            }
            else
            {
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }
                
        }


        public List<ProdutoDTO> ListaPorNome(string nomeProduto)
        {
            //ProdutoDAO produtoDAO = new ProdutoDAO();
           
            List<ProdutoDTO> listaProdutos = _context.CarregarProdutos(nomeProduto);
            return listaProdutos;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ApiService.DAO;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.DAO;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Validações;

namespace Projeto_Estoque.Controllers
{
    public class LoginController : Controller
    {

        private readonly UsuarioDAO _context;
        public LoginController(DataContext dataContext)
        {
            _context = new UsuarioDAO(dataContext);
        }
        public IActionResult Login(Usuario usuario)
        {     
                return View("\\Views\\Home\\Login.cshtml");
        }

        public IActionResult Logar(Usuario usuario)
        {
            
            


            if (!_context.carregarUsuario(usuario))
            {
                ModelState.AddModelError("Email", "Email ou senha estão incorretos");
                ModelState.AddModelError("Senha", "Email ou senha estão incorretos");
            }      
            if (ModelState.IsValid)
            {
                usuario = Usuario.GetInstance();
                return RedirectToAction("CarregarProdutos", "Home");
            }
            else
            {

                return View("\\Views\\Home\\Login.cshtml");
            }
        }

        
        public IActionResult Sair()
        {
            LoginValidacao.SairSistema();
            return Login(Usuario.GetInstance());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Validações;
using Projeto_Estoque.Enumerador;
using Projeto_Estoque.DAO;
using ApiService.DAO;

namespace Projeto_Estoque.Controllers
{
    public class RelatorioController : Controller
    {

        private readonly RelatorioDAO _context;
        public RelatorioController(DataContext dataContext)
        {
            _context = new RelatorioDAO(dataContext);
        }
        public IActionResult Relatorio()
        {
            TipoPerfil tipoPerfil = (TipoPerfil) LoginValidacao.ValidaPerfil();
            List<Relatorio> listaRelatorio = _context.carregarRelatorio();
            if(listaRelatorio == null || listaRelatorio.Count < 1)
                return View("\\Views\\Home\\Relatorio.cshtml");
            if (tipoPerfil == TipoPerfil.Usuario || tipoPerfil == TipoPerfil.Administrador)
            {
                
                return View("\\Views\\Home\\Relatorio.cshtml", listaRelatorio);
            }
            else
            {
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }
        }     

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


     
 
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

            </div>

            <div class="navbar-collapse collapse">


                </div>

            </div>

    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>

        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    </body>
</html>

Views/Shared/_LayoutLogado.cshtml
@*@model  List<Projeto_Estoque.Elementos.DTO.ProdutoDTO>*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jQueryMask/jquery.mask.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>


    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />


    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="CarregarProdutos" class="navbar-brand">Projeto Estoque</a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Cadastro" asp-action="Cadastro">Cadastro</a></li>
                    <li><a asp-area="" asp-controller="Relatorio" asp-action="Relatorio">Relatório</a></li>
                    <li><a asp-area="" asp-controller="Transacao" asp-action="Transacao">Perda/Venda</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Sair">Sair</a></li>
                    <li>
                        <form  method="post" action="/Consulta/Consulta">
                            <div class="form-group">                                
                                <div style="margin: 10px;">
                                    <input id="textinput" name="nomeProduto" type="text" style="border: 1px solid #ccc;border-radius: 4px;" />
                                    <button>Pesquisar</button>
                                </div>
                            </div>
                        </form>
                    </li>
</ul>
                <span class="fa fa-search form-control-feedback"></span>
                <div class="form-group" style="float:right;align-items: center;padding: 10px;">
                    
                    @*@{
                    Html.BeginForm("ConsultaProduto", "Consulta", FormMethod.Get))
                    {
                        
                        @Html.TextBoxFor(a => a[0].Nome)
                        <button  type="submit"><i class="glyphicon glyphicon-search"></i></button>

                    }*@

                </div>

            </div>
          
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr style="margin-top: 10%;"/>
        <footer>
            <p>&copy; 2020 - Projeto_Estoque</p>
        </footer>
    </div>

   
    @RenderSection("Scripts", required: false)
</body>
</html>