Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ApiService.DAO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Projeto_Estoque.DAO;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Validações;
using Projeto_Estoque.Elementos.DTO;
using Projeto_Estoque.Enumerador;

namespace Projeto_Estoque.Controllers
{
    public class CadastroController : Controller
    {

        private readonly ProdutoDAO _context;
        public CadastroController(DataContext dataContext)
        {
            _context = new ProdutoDAO(dataContext);          
        }
            public IActionResult Cadastro(ProdutoDTO produto)
        {

            TipoPerfil tipoPerfil = (TipoPerfil) LoginValidacao.ValidaPerfil();
            if (tipoPerfil == TipoPerfil.Administrador)
                return View("\\Views\\Home\\Cadastro.cshtml");
            else if (tipoPerfil == TipoPerfil.Usuario)
                return View("\\Views\\Home\\ErroAutorizacao.cshtml");
            else
            {   
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }

        }

        public IActionResult CadastrarProduto(ProdutoDTO produto)
        {
            
            Projeto_Estoque.Enumerador.TipoPerfil tipoPerfil =(Projeto_Estoque.Enumerador.TipoPerfil) LoginValidacao.ValidaPerfil();
            if (tipoPerfil == TipoPerfil.Administrador)
            {
                if (ModelState.TryGetValue("Id", out ModelStateEntry ObjetoValorId))
                    ObjetoValorId.Errors.Clear();

                if (!ProdutoValidacao.ValidaCategoria(produto))
                    ModelState.AddModelError("Categoria", "Categoria do produto é um campo obrigatório!");
                if (!ProdutoValidacao.ValidaNome(produto))
                    ModelState.AddModelError("Nome", "Nome do produto é um campo obrigatório!");
                if (!ProdutoValidacao.ValidaLote(produto))
                    ModelState.AddModelError("Lote", "Lote do produto é um campo obrigatório!");
                if (!ProdutoValidacao.ValidaQuantidade(produto))
                    ModelState.AddModelError("Quantidade", "Quantidade do produto não pode ser menor que 1!");
                if (!ProdutoValidacao.ValidaDataEntrada(produto))
                {
                    if (ModelState.TryGetValue("DataEntrada", out ModelStateEntry ObjetoValor))
                        ObjetoValor.Errors.Clear();
                    
                    ModelState.AddModelError("DataEntrada", "Data de Entrada do produto é um campo obrigatório!");
                }
                if (!ProdutoValidacao.ValidaPreco(produto))
                {
                    if (ModelState.TryGetValue("Valor", out ModelStateEntry ObjetoValor))
                        ObjetoValor.Errors.Clear();
                    ModelState.AddModelError("Valor", "Valor do produto é um campo obrigatório e maior que 0!");
                  
                }
               

                if (ModelState.IsValid)
                {

                    if (_context.SalvarProduto(produto))
                    {
                        ViewData["Message"] = "Produto Cadastrado com sucesso!";
                        return RedirectToAction("Cadastro", new { id = "Sucesso" });
                    }
                    else
                    {
                        ViewData["Message"] = "Erro ao cadastrar o produto!";
                        return View("\\Views\\Home\\Cadastro.cshtml");
                    }
                }
                else
                {
                    ViewData["Message"] = "";
                    return View("\\Views\\Home\\Cadastro.cshtml");
                }
                
            }
            else if (tipoPerfil == TipoPerfil.Usuario)
                return View("\\Views\\Home\\ErroAutorizacao.cshtml");
            else
            {
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }
        }

        
     
     
        

        public IActionResult AlterarProduto(string codigo, string lote)
        {
            ProdutoDTO produto = _context.consultarProduto(codigo, lote);
           
            return View("\\Views\\Home\\Cadastro.cshtml", produto);

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/CadastroUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ApiService.DAO;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.DAO;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Validações;

namespace Projeto_Estoque.Controllers
{
    public class CadastroUsuarioController : Controller
    {
        private readonly UsuarioDAO _context;
        public CadastroUsuarioController(DataContext dataContext)
        {
            _context = new UsuarioDAO(dataContext);
        }
        public IActionResult Cadastro(Usuario novoUsuario)
        {
            return View("\\Views\\Home\\CadastroUsuario.cshtml");
        }
        public IActionResult Cadastrar(Usuario usuario)
        {
            if (!LoginValidacao.ValidaEmail(usuario.email))
                ModelState.AddModelError("Email", "Email está em um formato incorreto. Exemplo correto: Email@email.com");
            if (!LoginValidacao.ValidaSenha(usuario.Senha))
                ModelState.AddModelError("Senha", "Minímo de 6 caracteres e máximo de 16");
            //LoginValidacao.CarregaTipoPerfil(usuario);
            if (_context.validarEmail(usuario))
            { 
                ModelState.AddModelError("Email", "Email já está cadastrado!");
            }
            if (ModelState.IsValid)
            {
                if (_context.SalvarUsuario(usuario))
                {
                    return RedirectToAction("CarregarProdutos", "Home");
                }
                else
                {
                    ViewData["Title"] = "Erro ao salvar novo Usuário do sistema.";
                    return View("\\Views\\Home\\CadastroUsuario.cshtml");
                }
            }
            else
            {

                return View("\\Views\\Home\\CadastroUsuario.cshtml");
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ApiService.DAO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.DAO;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Elementos.DTO;
using Projeto_Estoque.Validações;
using Projeto_Estoque.Enumerador;
namespace Projeto_Estoque.Controllers
{
   
    public class ConsultaController : Controller
    {
       

        private readonly ProdutoDAO _context;
        public ConsultaController(DataContext dataContext)
        {
            _context = new ProdutoDAO(dataContext);
        }

        public IActionResult Consulta(string NomeProduto)
        {

            TipoPerfil tipoPerfil = (TipoPerfil)LoginValidacao.ValidaPerfil();
            ViewData["Message"] = NomeProduto;
            if (tipoPerfil == TipoPerfil.Administrador || tipoPerfil == TipoPerfil.Usuario)
                return View("\\Views\\Home\\Consulta.cshtml");          
            else
            {
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }

        }

        public ActionResult<List<ProdutoDTO>> ConsultaProduto(ProdutoDTO produto)
        {
           
            

            Enumerador.TipoPerfil tipoPerfil = (Enumerador.TipoPerfil) LoginValidacao.ValidaPerfil();

           // List<Produto> listaProdutos =  _context.CarregarProdutos(produto.Nome);
            if (tipoPerfil == Enumerador.TipoPerfil.Usuario || tipoPerfil == Enumerador.TipoPerfil.Administrador)
            {
                
                return View("\\Views\\Home\\Consulta.cshtml");               
            }
            else
            {
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }
                
        }


        public List<ProdutoDTO> ListaPorNome(string nomeProduto)
        {
            //ProdutoDAO produtoDAO = new ProdutoDAO();
           
            List<ProdutoDTO> listaProdutos = _context.CarregarProdutos(nomeProduto);
            return listaProdutos;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ApiService.DAO;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.DAO;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Elementos.DTO;
using Projeto_Estoque.Validações;

namespace Projeto_Estoque.Controllers
{
    public class HomeController : Controller
    {

        private readonly ProdutoDAO _context;
        public HomeController(DataContext dataContext)
        {
            _context = new ProdutoDAO(dataContext);
            CarregarProdutos();
        }
        public IActionResult Index()
        {
           Enumerador.TipoPerfil tipoPerfil = (Enumerador.TipoPerfil) LoginValidacao.ValidaPerfil();

            if (tipoPerfil == Enumerador.TipoPerfil.Usuario || tipoPerfil == Enumerador.TipoPerfil.Administrador)
            {
                return View("\\Views\\Home\\Index.cshtml");
            }
            else
            {
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }
           
        }
        public ActionResult CarregarProdutos()
        {
            List<ProdutoDTO> listaProdutos = _context.listarProdutos();
           
            return View("\\Views\\Home\\Index.cshtml", listaProdutos);

        }






        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ApiService.DAO;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.DAO;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Validações;

namespace Projeto_Estoque.Controllers
{
    public class LoginController : Controller
    {

        private readonly UsuarioDAO _context;
        public LoginController(DataContext dataContext)
        {
            _context = new UsuarioDAO(dataContext);
        }
        public IActionResult Login(Usuario usuario)
        {     
                return View("\\Views\\Home\\Login.cshtml");
        }

        public IActionResult Logar(Usuario usuario)
        {
            
            


            if (!_context.carregarUsuario(usuario))
            {
                ModelState.AddModelError("Email", "Email ou senha estão incorretos");
                ModelState.AddModelError("Senha", "Email ou senha estão incorretos");
            }      
            if (ModelState.IsValid)
            {
                usuario = Usuario.GetInstance();
                return RedirectToAction("CarregarProdutos", "Home");
            }
            else
            {

                return View("\\Views\\Home\\Login.cshtml");
            }
        }

        
        public IActionResult Sair()
        {
            LoginValidacao.SairSistema();
            return Login(Usuario.GetInstance());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Projeto_Estoque.Elementos;
using Projeto_Estoque.Validações;
using Projeto_Estoque.Enumerador;
using Projeto_Estoque.DAO;
using ApiService.DAO;

namespace Projeto_Estoque.Controllers
{
    public class RelatorioController : Controller
    {

        private readonly RelatorioDAO _context;
        public RelatorioController(DataContext dataContext)
        {
            _context = new RelatorioDAO(dataContext);
        }
        public IActionResult Relatorio()
        {
            TipoPerfil tipoPerfil = (TipoPerfil) LoginValidacao.ValidaPerfil();
            List<Relatorio> listaRelatorio = _context.carregarRelatorio();
            if(listaRelatorio == null || listaRelatorio.Count < 1)
                return View("\\Views\\Home\\Relatorio.cshtml");
            if (tipoPerfil == TipoPerfil.Usuario || tipoPerfil == TipoPerfil.Administrador)
            {
                
                return View("\\Views\\Home\\Relatorio.cshtml", listaRelatorio);
            }
            else
            {
                Usuario.DisconectarUsuario();
                return View("\\Views\\Home\\Login.cshtml");
            }
        }     

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/About - Cópia.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Cadastro.cshtml
@model Projeto_Estoque.Elementos.DTO.ProdutoDTO
@{
    Layout = "_LayoutLogado";
}
@{
    ViewData["Title"] = "Cadastro de Produtos";


}
@{
    Usuario usuario = Usuario.GetInstance();
}

<h2>@ViewData["Title"]</h2>
<h3 style="margin-top:3%">@ViewData["Message"]</h3>
<h3 style="margin-top:3%" id="MensagemCadastroProduto"></h3>
<script>
    $(document).ready(function () {
        // your code

        var str = window.location.href;
        var parametro = "Sucesso";
        var aux = str.substring(str.length, str.length - parametro.length);
        $("#MensagemCadastroProduto").html("");
        var params = getSearchParameters();
        if (aux == 'Sucesso')
            $("#MensagemCadastroProduto").html("Produto Cadastrado com sucesso!");

        //else if (JSON.stringify(params).length >2 'undefined' || params != null) {
        //    $.ajax({
        //        type: "GET",
        //        url: "/Cadastro/ConsultarProduto/",
        //        contentType: 'application/json',
        //        data: parametro,
        //        success: function (data) {


        //            $('#NomeProduto').text = data.nome;
        //            $('#CategoriaProduto').text = data.categoria;
        //            $('#CodigoProduto').text = data.codigo;
        //            $('#LoteProduto').text = data.lote;
        //            $('#ValorProduto').val = data.valor;
        //            $('#DescricaoProduto').text = data.descricao;
        //            $('#LoteProduto').text = data.lote;

                    @*@if (usuario.TipoPerfil != TipoPerfil.Administrador)
                        {

                              $('#NomeProduto').attr('disabled');
                        $('#CategoriaProduto').attr('disabled');
                        $('#ValorProduto').attr('disabled');
                        $('#DescricaoProduto').attr('disabled');

                        }*@

            //    },

            //});
       // }
     

    });
</script>
@using (Html.BeginForm("CadastrarProduto", "Cadastro", FormMethod.Post))
{
    @if (usuario.TipoPerfil ==(int) Projeto_Estoque.Enumerador.TipoPerfil.Usuario)
    {
<div style="display:grid; width:50%">

    @Html.TextBoxFor(a => a.IdProduto, new { id = "IdProduto", style = "visibility:hidden" })


    @Html.Label("Produto")
    @Html.TextBoxFor(a => a.Nome, new { id = "NomeProduto", disabled = "true" })
    @Html.ValidationMessageFor(x => x.Nome)

    @Html.Label("Codigo")
    @Html.TextBoxFor(a => a.Codigo, new { id = "CodigoProduto", disabled = "true" })


    @Html.Label("Lote")
    @Html.TextBoxFor(a => a.Lote, new { id = "LoteProduto", disabled = "true" })
    @Html.ValidationMessageFor(x => x.Lote)

    @Html.Label("Quantidade")
    @Html.TextBoxFor(a => a.Quantidade, new { id = "QuantidadeProduto", disabled = "true" })
    @Html.ValidationMessageFor(x => x.Quantidade)

    @Html.Label("Categoria")
    @Html.TextBoxFor(a => a.Categoria, new { id = "CategoriaProduto", disabled = "true" })
    @Html.ValidationMessageFor(x => x.Categoria)


    @Html.Label("Data Entrada")
    @Html.EditorFor(a => a.DataEntrada, "{0:dd/MM/yyyy}", new { id = "DataEntradaProduto", disabled = "true" })
    @Html.ValidationMessageFor(x => x.DataEntrada)

    @Html.Label("Preço")
    @Html.TextBoxFor(a => a.Valor, new { @class = "money", id = "ValorProduto", disabled = "true" })
    @Html.ValidationMessageFor(x => x.Valor)

    @Html.Label("Descrição")
    @Html.TextAreaFor(a => a.Descricao, new { style = "Resize:none; overflow: hidden;height: 160%", id = "DescricaoProduto", disabled = "true" })
    @Html.ValidationMessageFor(x => x.Descricao)


    <button id="btnSalvarProduto" type="submit" style="margin-top: 10%; width:25%; visibility:hidden">Salvar  </button>
</div>
    }
    else if ((usuario.TipoPerfil ==(int) Projeto_Estoque.Enumerador.TipoPerfil.Administrador))
    {
<div style="display:grid; width:50%">
    @Html.TextBoxFor(a => a.IdProduto, new { id = "IdProduto", style = "visibility:hidden" })

    @Html.Label("Produto")
    @Html.TextBoxFor(a => a.Nome, new { id = "NomeProduto" })
    @Html.ValidationMessageFor(x => x.Nome)

    @Html.Label("Codigo")
    @Html.TextBoxFor(a => a.Codigo, new { id = "CodigoProduto", @readonly = "readonly" })


    @Html.Label("Lote")
    @Html.TextBoxFor(a => a.Lote, new { id = "LoteProduto" })
    @Html.ValidationMessageFor(x => x.Lote)

    @Html.Label("Quantidade")
    @Html.TextBoxFor(a => a.Quantidade, new { id = "QuantidadeProduto" })
    @Html.ValidationMessageFor(x => x.Quantidade)

    @Html.Label("Data Entrada")
    @Html.EditorFor(a => a.DataEntrada, "{0:dd/MM/yyyy}", new { id = "DataEntradaProduto" })
    @Html.ValidationMessageFor(x => x.DataEntrada)

    @Html.Label("Categoria")
    @Html.TextBoxFor(a => a.Categoria, new { id = "CategoriaProduto" })
    @Html.ValidationMessageFor(x => x.Categoria)

    @Html.Label("Preço")
    @Html.TextBoxFor(a => a.Valor, new { @class = "money", id = "ValorProduto" })
    @Html.ValidationMessageFor(x => x.Valor)

    @Html.Label("Descrição")
    @Html.TextAreaFor(a => a.Descricao, new { style = "Resize:none; overflow: hidden;height: 160%", id = "DescricaoProduto" })
    @Html.ValidationMessageFor(x => x.Descricao)

    <button id="btnSalvarProduto" type="submit" style="margin-top: 10%; width:25%;">Salvar  </button>
</div>
    }


}

<form action="/Home/Index" method="get">
    <input type="submit" value="Cancelar" id="frm1_submit" style="width:12.5%" />
</form>

Views/Home/CadastroUsuario.cshtml
@model Usuario
@{
    ViewData["Title"] = "Login Usuário";
}
<h2>@ViewData["Title"]</h2>


@using (Html.BeginForm("Cadastrar", "CadastroUsuario", FormMethod.Post))
{
<div style="display:grid; width:25%;">
    @Html.Label("Email")
    @Html.TextBoxFor(a => a.email)
     @Html.ValidationMessageFor(x => x.email)

    @Html.Label("Senha")
    @Html.TextBoxFor(a => a.Senha)
      @Html.ValidationMessageFor(x => x.Senha)

    @{
            List<SelectListItem> listItems = new List<SelectListItem>();
            listItems.Add(new SelectListItem
            {
                Text = "Usuario",
                Value = "2",
                Selected = true
            });
            listItems.Add(new SelectListItem
            {
                Text = "Administrador",
                Value = "1"

            });
        }
        @Html.DropDownListFor(model => model.TipoPerfil, listItems, new {style="margin-top: 10px;" })
</div>
    <button type="submit" style="margin-top:10px;">Salvar</button>

}

Views/Home/Consulta.cshtml
@model Projeto_Estoque.Elementos.DTO.ProdutoDTO
@{
    Layout = "_LayoutLogado";
    Usuario usuario = Usuario.GetInstance();
}
@{
    ViewData["Title"] = "Consulta Produto";
}
<h2>@ViewData["Title"]</h2>
<h3 id="MensagemCadastroProduto">@ViewData["Message"]</h3>



<script>
    var listaObjeto = [];
    var dataObject;

  
    dataObject = {
        "name": document.getElementById("MensagemCadastroProduto").innerText
    }
      

    function consultaProdutos() {

        var dataValue = {
            "nomeProduto": document.getElementById("MensagemCadastroProduto").innerText,
        };
       
        $.ajax({
            type: "GET",
            url: "/Consulta/ListaPorNome/",
           contentType: 'application/json; charset=utf-8',
           dataType: 'json',
            data:dataValue ,            
            success: function (data) {
                listaObjeto = data;
             //   $("#MensagemCadastroProduto").html(data.categoria);
                criarListaProdutos();
            },
           
        });
    }
    consultaProdutos();

    @*function criarListaProdutos() {
        for (var i = 0; i < listaObjeto.length; i++) {

            var objeto = listaObjeto[i];
            var lista = document.createElement('li');
            var link = document.createElement('a');
            link.setAttribute('href', '@Url.Action("AlterarProduto","Cadastro")' + '?Codigo=' + objeto.codigo + '&lote=' + objeto.lote
            )
            lista.appendChild(link);
            link.appendChild(document.createTextNode(objeto.nome + ' - ' + objeto.codigo + ' - ' + objeto.lote));
            var listaObjetos = document.getElementById('listaProdutos');
            listaObjetos.appendChild(lista);
            }
    }*@

     function criarListaProdutos() {
        for (var i = 0; i < listaObjeto.length; i++) {

            var objeto = listaObjeto[i];
            var lista = document.createElement('li');
            var produto = document.createElement('p');
            produto.classList.add("textoConsulta");
            lista.appendChild(produto);
            produto.appendChild(document.createTextNode(objeto.nome + ' - ' + objeto.codigo + ' - ' + objeto.lote));

            
            var linkAlterarProduto = document.createElement('a');
            linkAlterarProduto.classList.add("linkConsulta");
            linkAlterarProduto.setAttribute('href', '@Url.Action("AlterarProduto","Cadastro")' + '?Codigo=' + objeto.codigo + '&lote=' + objeto.lote
            );
            linkAlterarProduto.appendChild(document.createTextNode("Alterar produto"));

            var linkAlterarPorLote = document.createElement('a');
            linkAlterarPorLote.classList.add("linkConsulta");
            linkAlterarPorLote.setAttribute('href', '@Url.Action("Transacao","Transacao")' + '?Codigo=' + objeto.codigo + '&lote=' + objeto.lote
            );
            linkAlterarPorLote.appendChild(document.createTextNode("Perda/Venda"));
            
            @*var addPerdaVenda = document.createElement('a');
            addPerdaVenda.classList.add("linkConsulta");
            addPerdaVenda.setAttribute('href', '@Url.Action("PerdaVenda","Cadastro")' + '?Codigo=' + objeto.codigo
            );
            addPerdaVenda.appendChild(document.createTextNode("Perda/Venda"));*@ 

            lista.appendChild(linkAlterarProduto);
            lista.appendChild(linkAlterarPorLote);
            //lista.appendChild(addPerdaVenda);


            var listaObjetos = document.getElementById('listaProdutos');
            listaObjetos.appendChild(lista);
            }
    }


    
    //function consultaProduto(indice) {
        
    //    var Produto = new Object();
    //    Produto.Nome = listaObjeto[indice].nome;
    //    Produto.Descricao = listaObjeto[indice].descricao;
    //    Produto.Codigo = listaObjeto[indice].codigo;
    //    Produto.Valor = listaObjeto[indice].valor;
    //    Produto.Categoria = listaObjeto[indice].categoria;


    //    $.ajax({
    //        type: 'POST',
    //        url: '/Cadastro/ConsultarProduto/',
    //        dataType: 'json',
    //        data:  Produto,
    //        success: function (data) {
    //            redirecionamento = data;
    //        },
    //    });
    //}
  
   

</script>
<div>
    
    <p>Produtos:</p>

    <ul id="listaProdutos"></ul>

</div>

Views/Home/ErroAutorizacao.cshtml
@{
    Layout = "_LayoutLogado";
}
@{
    ViewData["Title"] = "Não Autorizado";
}
<div style="margin:15%">
    <b> Você não tem autorização para acessar essa página. Contacte o administrador do Sistema.</b>
    <a asp-area="" asp-controller="Home" asp-action="Index">Voltar</a>
</div>

Views/Home/Index.cshtml
@model IEnumerable<Projeto_Estoque.Elementos.DTO.ProdutoDTO>
@*@model Projeto_Estoque.Elementos.DTO.ProdutoDTO*@

@*@Html.Partial("~/Views/Shared/_LayoutLogado.cshtml", new Projeto_Estoque.Elementos.DTO.ProdutoDTO())*@
@{

    Layout = "_LayoutLogado";

}
@{
    ViewData["Title"] = "Projeto Estoque";
}

<div>
    <div class="divTable">
        <h3>Resumo Estoque</h3>
        <table id="tg-xQLBb" class="tg">
            <thead>
                <tr>
                    <th class="tg-ul38">Código</th>
                    <th class="tg-ul38">Produto</th>
                    <th class="tg-ul38">Categoria</th>
                    <th class="tg-ul38">Valor</th>
                    <th class="tg-ul38">Estoque</th>
                    <th class="tg-ul38">Lote</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                <tr>


                    <td class="tg-0lax">@item.Codigo </td>
                    <td class="tg-0lax">@item.Nome</td>
                    <td class="tg-0lax">@item.Categoria</td>
                    <td class="tg-0lax">@item.Valor</td>
                    <td class="tg-0lax">@item.Quantidade</td>
                    <td class="tg-0lax">@item.Lote</td>
                </tr>
                    }
                }

            </tbody>
        </table>
    </div>
</div>

Views/Home/Login.cshtml
@model Usuario
@{
    ViewData["Title"] = "Login Usuário";
}
<h2>@ViewData["Title"]</h2>

@using (Html.BeginForm("Logar", "Login", FormMethod.Post))
{
<div>
    @Html.Label("Email: ")
    @Html.TextBoxFor(a => a.email, new { style = "margin-left: 10px;" })
    @Html.ValidationMessageFor(a => a.email)
</div>
   

<div>
    @Html.Label("Senha: ")
    @Html.PasswordFor(a => a.Senha, new { style = "margin-left: 5px;" })
    @Html.ValidationMessageFor(x => x.Senha)

</div>
    <button type="submit" style="margin: 10px 10px 10px 40px;">Logar <i class="glyphicon glyphicon-user"></i></button>
    
}

@using (Html.BeginForm("Cadastro", "CadastroUsuario", FormMethod.Post))
{
    <div>
        <p> </p>
        <button type="submit" style="margin: 10px 10px 10px 40px;">Cadastrar usuário</button>
    </div>


}

Views/Home/UsuarioCadastro.cshtml
@{
    ViewData["Title"] = "Cadastro Realizado com sucesso";
}
<h2>@ViewData["Title"]</h2>

<li><a asp-area="" asp-controller="Login" asp-action="Login">Relatório</a></li>